# Generated by Django 3.2.14 on 2022-10-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataListrik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.CharField(max_length=10)),
                ('voltage', models.CharField(max_length=10)),
                ('current', models.CharField(max_length=10)),
                ('power', models.CharField(max_length=10)),
                ('frequency', models.CharField(max_length=10)),
                ('power_factor', models.CharField(max_length=10)),
                ('current_ch1', models.CharField(max_length=10)),
                ('current_ch2', models.CharField(max_length=10)),
                ('current_ch3', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'ID_Datalogger',
            },
        ),
        migrations.CreateModel(
            name='TestSimpan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.CharField(max_length=10)),
                ('data1', models.CharField(max_length=10)),
                ('data2', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Test_Simpan',
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profileimg',
        ),
    ]
